language: csharp
mono: none
dotnet: 2.0.0
solution: CourseRegistrationManagementSystem.sln
script:
  - cd CourseRegistrationManagementSystem
  - dotnet restore
  - dotnet build -c Release
  - dotnet test CourseRegistrationManagementSystem.Tests
  